---
dependency:
  name: galaxy
  options:
    requirements-file: .requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint ../arillso.wireguard
  flake8
platforms:
  - name: ubuntu-xenial
    image: arillso/ubuntu:xenial
    privileged: true
    command: /lib/systemd/systemd
    cap_add:
      - ALL
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /dev:/dev
      - /lib/modules:/lib/modules
    sysctls:
      net.ipv4.ip_forward: 1
provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
  env:
    ANSIBLE_ROLES_PATH: ../../
verifier:
  name: ansible
