---
dependency:
  name: galaxy
  options:
    requirements-file: .requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint ../arillso.wireguard
  flake8
platforms:
  - name: alpine-3.12
    image: arillso/alpine:3.12
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
  env:
    ANSIBLE_ROLES_PATH: ../../
verifier:
  name: ansible
