---
# tasks file for arillso.wireguard

- name: 'ArchLinux : Install wireguard-lts package'
  become: true
  pacman:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
  with_items:
    - name: wireguard-dkms
      state: absent
    - name: wireguard-lts
      state: present
  when:
    - ansible_kernel is match(".*-lts$")
    - ansible_kernel is version('5.6', '<')

- name: 'ArchLinux : Install wireguard-dkms package'
  become: true
  pacman:
    name: wireguard-dkms
    state: present
  when:
    - not ansible_kernel is match(".*-lts$")
    - ansible_kernel is version('5.6', '<')

- name: 'ArchLinux : Install wireguard-tools package'
  pacman:
    name: wireguard-tools
    state: present
