---
# tasks file for arillso.wireguard

- name: 'Ubuntu : Install support packages needed for Wireguard (for Ubuntu < 19.10)'
  become: true
  ansible.builtin.apt:
    name: '{{ packages }}'
    state: present
    update_cache: true
  vars:
    packages:
      - software-properties-common
      - linux-headers-{{ ansible_kernel }}
  when:
    - ansible_lsb.major_release is version('19.10', '<')

- name: 'Ubuntu : Ensure WireGuard DKMS package is removed'
  become: true
  ansible.builtin.apt:
    name:
      - 'wireguard-dkms'
    state: absent
    update_cache: true

- name: 'Ubuntu : Install wireguard package'
  become: true
  ansible.builtin.apt:
    name: 'wireguard'
    state: present
    update_cache: true
