---
name: Role Release
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    name: Role Release Test

    defaults:
      run:
        working-directory: arillso.wireguard

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: arillso.wireguard

      - name: Ansible Molecule Test
        uses: gofrolist/molecule-action@v2.0.1
        with:
          molecule_command: test
          molecule_working_dir: arillso.wireguard

  publish:
    runs-on: ubuntu-latest

    name: Role Release Publish

    if: always()
    needs:
      - release

    steps:
      - name: Release Ansible Role to Galaxy
        uses: hspaans/ansible-galaxy-action@v0.2.0
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
