---
name: Role Release
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    name: Role Release Test

    defaults:
      run:
        working-directory: arillso.wireguard

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: arillso.wireguard

      - name: Test Ansible with Molecule
        uses: arillso/action.molecule@0.0.1
        with:
          molecule_command: test
          molecule_working_dir: arillso.wireguard

  publish:
    runs-on: ubuntu-latest

    name: Role Release Publish

    if: always()
    needs:
      - release

    steps:
      - name: Release Ansible Role to Galaxy
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
